# Generated by Django 5.0.4 on 2024-04-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_product_seller_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(default='Seller', max_length=50),
        ),
    ]
