# Generated by Django 5.0.4 on 2024-04-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_product_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='mobno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller_name',
            field=models.CharField(max_length=30),
        ),
    ]
