# Generated by Django 5.0.4 on 2024-04-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_contact_desc_alter_contact_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='../shop/static/shop/default.png', upload_to='shop/images'),
        ),
    ]
